### ISSUE TITLE
Breaking advanced storage turn into basic storage 

### ISSUE THREAD

**Issue by zwrumpy** [Mooy1/InfinityExpansion#78]
## Description (Required)
advanced storage units just don't work as they should, 
breaking them voids the contained stuff 
and makes it back to a basic storage unit

## Steps to reproduce the Issue (Required)
1. open advance storage inventory
2. break the block
3. block turn into basic storage and no sf inventory

screenrecord link:
https://gyazo.com/96dc47c767afc93b3ace055706191f6f

## Expected behavior (Required)
break block and give advance storage

## Server Log / Error Report
no error log

## Environment (Required)
 - Minecraft Version: 1.17.1 papermc
 - Slimefun Version: slimefun dev 971
 - Plugin Version:   InfinityExpansion DEV - 123

**Comment by AN0NISN4P** [comment]
# Tested in Slimefun DEV - 972
***This seems to still randomly occur***

Had the same issue happen, just with some Infinity Storage Units. I decided to test around with them, seeing if I could find a way to identify them.

### Spotting it
What I found was, the signs showing the contents of the Storage Units would be stuck on whatever was in them when breaking, well more a case of the Signs not updating at all, new signs would simply not change to show contents. On top of this, they only had the items in the Left most slot, example [here](https://gyazo.com/da5f4972eeb71682479306be94ed8c76).

### Effects of this
Though what happened with the Storage Units themselves, from the players perspective, was it working as a trashcan, voiding items. I forgot to test if it was due to Void Excess being on, which might have caused the extra to be voided, if it though it was full. Also forgot to test if the units would void any item you put into it.

### Reasons
As for reasons on what caused it, it's basically a total mystery. At the time my storage units broke, they had been working fine for roughly 3 days time, going through the Server Rebooting as well. All the Storage Units which I found to have broken were all placed within a couple of minutes of each other, though a nearby Storage Unit of the same tier, placed nearly 12 hours later was working fine. 

## Summary
Storage Units dropping as a Basic Storage Unit can still happen.
I've found no way to force this to happen. Though all the affected units were placed nearly the same time
<br>

**How to spot a broken unit**
- Items are not showing on the Output side
- Signs do not update when adding items into the unit
- Newly placed signs do not show the Item in the Storage Unit
<br>

**Things I forgot to test** *(Please test if a broken storage unit is found)*
- Do they void any item added into them?
- Do they void items because of "Void Excess" being turned on?

**Comment by Mooy1** [comment]
Could you post your startup logs, and make sure slimefuns log duplicate blocks option is enabled in the config.
